"""Public package for framework-neutral user management and authorization."""

from typing import Final

from my_usermanager.admin import (
    AdminGrantOperation,
    AdminUserGrantSummary,
    GrantAdminService,
    UnsafeGrantMutationError,
)
from my_usermanager.claims import (
    ClaimMapper,
    GrantClaims,
    GrantClaimsContext,
    GrantClaimsProjector,
    max_permission_level_claim,
    permission_claim,
    role_claim,
)
from my_usermanager.manager import (
    AuthorizationError,
    PermissionGrantRequest,
    RoleGrantRequest,
    UserManager,
    UserProfileUpdate,
)
from my_usermanager.memory import (
    MemoryAuditStore,
    MemoryGrantStore,
    MemoryRoleStore,
    MemoryUserStore,
)
from my_usermanager.models import (
    AuditEvent,
    ExternalIdentity,
    Grant,
    Permission,
    Role,
    Scope,
    User,
    ValidationError,
    validate_identifier,
    validate_permission_name,
)
from my_usermanager.permissions import (
    ADMIN_ROLE_NAME,
    BUILTIN_PERMISSION_NAMES,
    BUILTIN_PERMISSIONS,
    BUILTIN_ROLES,
    PermissionRegistry,
    UnregisteredPermissionError,
    is_valid_permission_name,
)
from my_usermanager.sessions import (
    SESSION_PRINCIPAL_KEY,
    InvalidSessionPrincipalError,
    SessionClaimValue,
    SessionPrincipal,
    SessionTokenStore,
    clear_session_principal,
    clear_token_principal,
    principal_template_context,
    read_session_principal,
    read_token_principal,
    refresh_session_principal,
    write_session_principal,
    write_token_principal,
)
from my_usermanager.stores import (
    AuditFilters,
    AuditStore,
    DuplicateAuditEventError,
    DuplicateGrantError,
    DuplicateUserError,
    GrantNotFoundError,
    GrantStore,
    InvalidPageError,
    RoleStore,
    SessionRevoker,
    StoreError,
    UserNotFoundError,
    UserQuery,
    UserStore,
)

__version__: Final = "0.1.0"

__all__: Final = (
    "ADMIN_ROLE_NAME",
    "BUILTIN_PERMISSIONS",
    "BUILTIN_PERMISSION_NAMES",
    "BUILTIN_ROLES",
    "SESSION_PRINCIPAL_KEY",
    "AdminGrantOperation",
    "AdminUserGrantSummary",
    "AuditEvent",
    "AuditFilters",
    "AuditStore",
    "AuthorizationError",
    "ClaimMapper",
    "DuplicateAuditEventError",
    "DuplicateGrantError",
    "DuplicateUserError",
    "ExternalIdentity",
    "Grant",
    "GrantAdminService",
    "GrantClaims",
    "GrantClaimsContext",
    "GrantClaimsProjector",
    "GrantNotFoundError",
    "GrantStore",
    "InvalidPageError",
    "InvalidSessionPrincipalError",
    "MemoryAuditStore",
    "MemoryGrantStore",
    "MemoryRoleStore",
    "MemoryUserStore",
    "Permission",
    "PermissionGrantRequest",
    "PermissionRegistry",
    "Role",
    "RoleGrantRequest",
    "RoleStore",
    "Scope",
    "SessionClaimValue",
    "SessionPrincipal",
    "SessionRevoker",
    "SessionTokenStore",
    "StoreError",
    "UnregisteredPermissionError",
    "UnsafeGrantMutationError",
    "User",
    "UserManager",
    "UserNotFoundError",
    "UserProfileUpdate",
    "UserQuery",
    "UserStore",
    "ValidationError",
    "__version__",
    "clear_session_principal",
    "clear_token_principal",
    "is_valid_permission_name",
    "max_permission_level_claim",
    "permission_claim",
    "principal_template_context",
    "read_session_principal",
    "read_token_principal",
    "refresh_session_principal",
    "role_claim",
    "validate_identifier",
    "validate_permission_name",
    "write_session_principal",
    "write_token_principal",
)
